#!/bin/bash

set -ex

#go install ./vendor/github.com/golang/protobuf/protoc-gen-go

for f in `find pkg/ -name "*.proto"`; do
  protoc --go_out=plugins=grpc:../.. $f
done

for f in `find pkg/ -name "*.pb.go"`; do
  cat > $f.tmp <<EOF
/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
EOF

  cat $f >> $f.tmp
  mv $f.tmp $f
done